soccer_review:
    resource: "@SoccerBundle/Controller/ReviewController.php"
    type:     annotation

soccer_player:
    resource: "@SoccerBundle/Controller/PlayerController.php"
    type:     annotation

soccer_player:
    resource: "@SoccerBundle/Controller/PlayerController.php"
    type:     annotation

secur:
    resource: "@SecurBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

soccer:
    resource: "@SoccerBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout
