secur:
    resource: "@SecurBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

soccer:
    resource: "@SoccerBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout
