<?php

namespace SoccerBundle\Repository;

/**
 * ListplayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListplayersRepository extends \Doctrine\ORM\EntityRepository
{
}
